name: test_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - fastp=0.24.1
  - numpy<2
  - cython
  - jinja2
  - tbb=2020.2
  - pyparsing=2.3.1
  - scipy
  - matplotlib=3.8.4
  - pandas>2
  - pytest-check
  - pip:
    - ydiff
